[tox]
envlist = py38, py39, py310, py311, py312, flake8
isolated_build = true

[testenv:flake8]
basepython = python3
usedevelop = true
extras =
    dev
    io
commands =
    flake8 cigarmath tests

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
usedevelop = true
extras =
    dev
    io
commands =
    python -m pip install -U pip
    pytest --basetemp={envtmpdir}
